steps:
  - name: 'node:12'
    entrypoint: 'npm'
    args: ['ci']

  - name: 'node:12'
    entrypoint: 'npm'
    args: ['run', 'build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/portfolio-ui:$TAG_NAME", "."]

images: ['gcr.io/$PROJECT_ID/portfolio-ui']
