steps:
  - name: 'node:12'
    entrypoint: 'npm'
    args: ['ci']

  - name: 'node:12'
    entrypoint: 'npm'
    args: ['run', 'lint']

  - name: 'node:12'
    entrypoint: 'npm'
    args: ['run', 'test']

  - name: 'node:12'
    entrypoint: 'npm'
    args: ['run', 'build']
